-- SELECT * --

SELECT * FROM Global_Sales;

-- Show me the Distinct Shoe brands in the database -- 

SELECT 
	DISTINCT(brand) AS Available_Brands 
FROM Global_Sales
ORDER BY brand ASC;

-- Select the revenue generated by each brand yearly -- 

SELECT
	brand AS Brands,
	SUM(revenue_usd) AS Total_Revenue,
	YEAR(order_date) AS Year
FROM Global_Sales
GROUP BY 
	brand, 
	YEAR(order_date)
ORDER BY 
	brand ASC, 
	Year(order_date) ASC;

-- Footwear model performance revenue wise in group by year and brand --

SELECT 
	brand AS BRAND,
	YEAR(order_date) AS Year,
	model_name,
	SUM(revenue_usd) AS Total_Revenue
FROM Global_Sales
GROUP BY 
	brand, 
	model_name,
	YEAR(order_date)
ORDER BY 
	brand ASC, 
	Year(order_date) ASC;